import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Cell from "../src/cell";
import Controller from "../src/controller";

const Home: NextPage = () => {
  const [srcs, setSrcs] = useState<string[]>(
    Array.from({ length: 60 }, () => `https://picsum.photos/seed/${Math.random()}/1000`)
  );
  const [cols, setCols] = useState<number>(3);
  const [rows, setRows] = useState<number>(6);

  const columnStyle = {
    gridTemplateColumns: `repeat(${cols}, auto)`,
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">Album Wallpaper Maker</h1>
        <p className="description">
          Ever wanted to make a personalized collage of albums for your wallpaper? Now you can.
        </p>

        <Controller onNewCols={(x: number) => setCols(x)} onNewRows={(x: number) => setRows(x)} />

        <div className="grid" style={columnStyle}>
          {srcs.slice(0, rows * cols).map((src, i) => (
            <Cell
              onSrcChange={_src => {
                const newSrcs = Array.from(srcs);
                newSrcs[i] = _src;
                console.log(srcs);
                console.log(newSrcs);
                setSrcs(newSrcs);
              }}
              initSrc={src}
              key={i}
            />
          ))}
        </div>

        <div className="download-btn">
          <button className="button-19">download</button>
        </div>
      </main>

      <footer></footer>
    </>
  );
};

export default Home;
